// {{name}} - Altos Plugin
// Generated by: altos create plugin {{name}}

import type { PluginAPI } from "@altos/plugins";

/**
 * Plugin implementation.
 * @param {PluginAPI} api - The plugin API
 */
export const plugin = {
  name: "{{name}}",
  version: "0.1.0",
  description: "{{description}}",

  async init(api: PluginAPI): Promise<void> {
    api.logger.info("{{name}} plugin initializing");

    // --- Register a tool ---
    // api.registerTool({
    //   name: "{{name}}/my-tool",
    //   description: "What this tool does",
    //   inputSchema: {
    //     type: "object",
    //     properties: {
    //       input: { type: "string", description: "Input value" },
    //     },
    //     required: ["input"],
    //   },
    //   async handler(args, ctx) {
    //     api.logger.debug("my-tool called with:", args);
    //     return { success: true, data: { result: args.input + " processed" }, duration: 0 };
    //   },
    // });

    // --- Register a slash command ---
    // api.registerCommand({
    //   name: "mycmd",
    //   description: "My custom command",
    // });

    // --- Register lifecycle hooks ---
    for (const event of [
      "session_start",
      "user_prompt",
      "before_model_call",
      "after_model_call",
      "before_tool_call",
      "after_tool_call",
      "before_file_write",
      "after_file_write",
      "before_compact",
      "session_end",
    ] as const) {
      api.registerHook({
        name: `{{name}}:log-${event}`,
        event,
        priority: 100,
        handler: async (ctx) => {
          api.logger.debug(`Hook: ${event}`, {
            sessionId: ctx.sessionId,
            data: ctx.data,
          });
        },
      });
    }

    // --- Register a memory provider ---
    // api.registerMemoryProvider(myMemoryProvider);

    // --- Register an MCP server ---
    // api.registerMcpServer({
    //   id: "{{name}}-mcp",
    //   name: "{{name}} MCP Server",
    //   command: "npx",
    //   args: ["-y", "@some/mcp-server"],
    // });

    // --- Register a skill ---
    // api.registerSkill({
    //   name: "{{name}}-skill",
    //   description: "My skill description",
    //   path: "./skills/my-skill.md",
    // });

    // --- Persist state ---
    // const count = (api.readConfig("call_count") as number) ?? 0;
    // api.writeConfig("call_count", count + 1);

    api.logger.info("{{name}} plugin initialized");
  },

  async dispose(): Promise<void> {
    // Clean up: close connections, save state, etc.
  },
};
