import { z } from "zod";
import { BASE_CHAIN_ID } from "@base-orchestrator/shared";

const booleanEnv = (defaultValue: boolean) =>
  z
    .preprocess(
      (value) => (value === undefined ? defaultValue : value),
      z.union([z.enum(["true", "false"]), z.boolean()]),
    )
    .transform((value) => value === true || value === "true");

const integerEnv = (defaultValue: number) =>
  z.preprocess(
    (value) => (value === undefined ? defaultValue : value),
    z.coerce.number().int().nonnegative(),
  );

const rawIntegerStringEnv = (defaultValue: string) =>
  z
    .preprocess(
      (value) => (value === undefined ? defaultValue : value),
      z.union([z.string().regex(/^(0|[1-9]\d*)$/), z.number().int().nonnegative()]),
    )
    .transform((value) => String(value));

const operatorPasswordHashEnv = z
  .string()
  .refine(
    (value) =>
      value.startsWith("$argon2id$") || /^sha256:[a-f0-9]{64}$/.test(value),
    "OPERATOR_PASSWORD_HASH must be an Argon2id encoded hash generated by pnpm auth:hash-password",
  )
  .optional();

const envSchema = z
  .object({
    NODE_ENV: z
      .enum(["development", "test", "production"])
      .default("development"),
    API_HOST: z.string().default("127.0.0.1"),
    API_PORT: integerEnv(4100),
    WEB_PORT: integerEnv(3100),
    DATABASE_URL: z
      .string()
      .url()
      .default(
        "postgresql://base_orchestrator:base_orchestrator@localhost:5435/base_orchestrator",
      ),
    REDIS_URL: z.string().url().default("redis://localhost:6379"),
    BASE_CHAIN_ID: integerEnv(BASE_CHAIN_ID),
    BASE_RPC_URL: z.string().url().default("https://mainnet.base.org"),
    BASESCAN_BASE_URL: z.string().url().default("https://basescan.org"),
    DRY_RUN: booleanEnv(true),
    DEMO_MODE: booleanEnv(true),
    REQUIRE_LIVE_CONFIRMATION: booleanEnv(true),
    ALLOW_UNLIMITED_APPROVAL: booleanEnv(false),
    AUTO_APPROVE: booleanEnv(false),
    SCHEDULER_LIVE_EXECUTION: booleanEnv(false),
    NATIVE_VALUE_SWAPS_ENABLED: booleanEnv(false),
    MAX_NATIVE_VALUE_WEI: rawIntegerStringEnv("0"),
    CONFIRMATIONS_REQUIRED: integerEnv(3),
    SUBMITTED_TX_TIMEOUT_MS: integerEnv(900000),
    TX_STUCK_AFTER_MINUTES: integerEnv(15),
    TX_DROPPED_AFTER_MINUTES: integerEnv(60),
    TX_REORG_LOOKBACK_BLOCKS: integerEnv(12),
    QUOTE_PROVIDER: z.enum(["mock", "0x", "zeroX"]).default("mock"),
    QUOTE_MAX_AGE_SECONDS: integerEnv(30),
    VAULT_PROVIDER: z
      .enum(["local-file", "kms", "external-signer", "external-http-signer"])
      .default("local-file"),
    MASTER_KEY_FILE: z.string().min(1).default(".local/master.key"),
    EXTERNAL_SIGNER_URL: z.string().url().optional(),
    EXTERNAL_SIGNER_TOKEN: z.string().optional(),
    EXTERNAL_SIGNER_MTLS: booleanEnv(false),
    EXTERNAL_SIGNER_CLIENT_CERT: z.string().optional(),
    EXTERNAL_SIGNER_CLIENT_KEY: z.string().optional(),
    EXTERNAL_SIGNER_HEALTH_URL: z.string().url().optional(),
    EXTERNAL_SIGNER_SIGN_TIMEOUT_MS: integerEnv(30000),
    EXTERNAL_SIGNER_NONCE_STRATEGY: z.enum(["rpc", "managed"]).default("rpc"),
    TELEGRAM_ENABLED: booleanEnv(false),
    OPERATOR_USERNAME: z.string().min(1).default("operator"),
    OPERATOR_PASSWORD_HASH: operatorPasswordHashEnv,
    OPERATOR_PASSWORD: z.string().optional(),
    OPERATOR_ROLE: z.enum(["viewer", "operator", "admin"]).default("admin"),
    SESSION_TTL_SECONDS: z.coerce.number().int().min(300).max(86400).default(43200),
    TOTP_ISSUER: z.string().default("BaseOrchestrator"),
    SESSION_SECRET: z
      .string()
      .min(32)
      .default("local-dev-session-secret-change-before-live"),
    VAULT_UNLOCK_PASSPHRASE: z.string().optional(),
    VAULT_AUTO_LOCK_MS: integerEnv(900000),
    WALLET_LOCK_TTL_MS: integerEnv(300000),
    ZEROX_SWAP_QUOTE_URL: z.string().url().optional(),
    ZEROX_API_KEY: z.string().optional(),
    ZEROX_API_VERSION: z.string().default("v2"),
    ALERT_WEBHOOK_URL: z.string().url().optional(),
    ALERT_WEBHOOK_TOKEN: z.string().optional(),
    METRICS_TOKEN: z.string().optional(),
  })
  .superRefine((env, context) => {
    if (env.BASE_CHAIN_ID !== BASE_CHAIN_ID) {
      context.addIssue({
        code: "custom",
        path: ["BASE_CHAIN_ID"],
        message: `BASE_CHAIN_ID must be ${BASE_CHAIN_ID}`,
      });
    }
    if (env.DEMO_MODE && !env.DRY_RUN) {
      context.addIssue({
        code: "custom",
        path: ["DEMO_MODE"],
        message: "DEMO_MODE=true requires DRY_RUN=true",
      });
    }
    if (env.SCHEDULER_LIVE_EXECUTION && env.DRY_RUN) {
      context.addIssue({
        code: "custom",
        path: ["SCHEDULER_LIVE_EXECUTION"],
        message: "SCHEDULER_LIVE_EXECUTION=true requires DRY_RUN=false",
      });
    }
    if (env.SCHEDULER_LIVE_EXECUTION && env.DEMO_MODE) {
      context.addIssue({
        code: "custom",
        path: ["SCHEDULER_LIVE_EXECUTION"],
        message: "SCHEDULER_LIVE_EXECUTION=true is blocked in demo mode",
      });
    }
    if (env.AUTO_APPROVE && env.ALLOW_UNLIMITED_APPROVAL) {
      context.addIssue({
        code: "custom",
        path: ["AUTO_APPROVE"],
        message: "AUTO_APPROVE cannot be combined with unlimited approvals",
      });
    }
    if (env.NODE_ENV === "production" && !env.DRY_RUN && env.VAULT_PROVIDER === "local-file") {
      context.addIssue({
        code: "custom",
        path: ["VAULT_PROVIDER"],
        message:
          "VAULT_PROVIDER=local-file is not permitted in production with live trading. " +
          "Use kms or external-signer. See docs/CUSTODY_HARDENING_ROADMAP.md.",
      });
    }
    if (env.NODE_ENV === "production") {
      if (!env.OPERATOR_PASSWORD_HASH) {
        context.addIssue({
          code: "custom",
          path: ["OPERATOR_PASSWORD_HASH"],
          message: "OPERATOR_PASSWORD_HASH is required in production",
        });
      }
      if (env.OPERATOR_PASSWORD) {
        context.addIssue({
          code: "custom",
          path: ["OPERATOR_PASSWORD"],
          message: "OPERATOR_PASSWORD is local development only",
        });
      }
      if (env.SESSION_SECRET === "local-dev-session-secret-change-before-live") {
        context.addIssue({
          code: "custom",
          path: ["SESSION_SECRET"],
          message: "SESSION_SECRET must be set explicitly in production",
        });
      }
      if (!env.METRICS_TOKEN) {
        context.addIssue({
          code: "custom",
          path: ["METRICS_TOKEN"],
          message: "METRICS_TOKEN is required in production",
        });
      }
    }
  });

const formatEnvError = (error: z.ZodError) =>
  error.issues
    .map((issue) => `${issue.path.join(".") || "env"}: ${issue.message}`)
    .join("; ");

export class RuntimeEnvError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RuntimeEnvError";
  }
}

export const parseRuntimeEnv = (env: Record<string, string | undefined>) => {
  const parsed = envSchema.safeParse(env);
  if (!parsed.success) {
    throw new RuntimeEnvError(formatEnvError(parsed.error));
  }

  return {
    nodeEnv: parsed.data.NODE_ENV,
    apiHost: parsed.data.API_HOST,
    apiPort: parsed.data.API_PORT,
    webPort: parsed.data.WEB_PORT,
    databaseUrl: parsed.data.DATABASE_URL,
    redisUrl: parsed.data.REDIS_URL,
    baseChainId: parsed.data.BASE_CHAIN_ID,
    baseRpcUrl: parsed.data.BASE_RPC_URL,
    basescanBaseUrl: parsed.data.BASESCAN_BASE_URL.replace(/\/+$/, ""),
    dryRun: parsed.data.DRY_RUN,
    demoMode: parsed.data.DEMO_MODE,
    requireLiveConfirmation: parsed.data.REQUIRE_LIVE_CONFIRMATION,
    allowUnlimitedApproval: parsed.data.ALLOW_UNLIMITED_APPROVAL,
    autoApprove: parsed.data.AUTO_APPROVE,
    schedulerLiveExecution: parsed.data.SCHEDULER_LIVE_EXECUTION,
    nativeValueSwapsEnabled: parsed.data.NATIVE_VALUE_SWAPS_ENABLED,
    maxNativeValueWei: parsed.data.MAX_NATIVE_VALUE_WEI,
    confirmationsRequired: parsed.data.CONFIRMATIONS_REQUIRED,
    submittedTxTimeoutMs: parsed.data.SUBMITTED_TX_TIMEOUT_MS,
    txStuckAfterMinutes: parsed.data.TX_STUCK_AFTER_MINUTES,
    txDroppedAfterMinutes: parsed.data.TX_DROPPED_AFTER_MINUTES,
    txReorgLookbackBlocks: parsed.data.TX_REORG_LOOKBACK_BLOCKS,
    quoteProvider: parsed.data.QUOTE_PROVIDER,
    quoteMaxAgeSeconds: parsed.data.QUOTE_MAX_AGE_SECONDS,
    masterKeyFile: parsed.data.MASTER_KEY_FILE,
    telegramEnabled: parsed.data.TELEGRAM_ENABLED,
    operatorUsername: parsed.data.OPERATOR_USERNAME,
    operatorPasswordHash: parsed.data.OPERATOR_PASSWORD_HASH ?? null,
    operatorPassword: parsed.data.OPERATOR_PASSWORD ?? null,
    sessionSecret: parsed.data.SESSION_SECRET,
    operatorRole: parsed.data.OPERATOR_ROLE,
    sessionTtlSeconds: parsed.data.SESSION_TTL_SECONDS,
    totpIssuer: parsed.data.TOTP_ISSUER,
    vaultUnlockPassphrase: parsed.data.VAULT_UNLOCK_PASSPHRASE ?? null,
    vaultAutoLockMs: parsed.data.VAULT_AUTO_LOCK_MS,
    walletLockTtlMs: parsed.data.WALLET_LOCK_TTL_MS,
    zeroXSwapQuoteUrl: parsed.data.ZEROX_SWAP_QUOTE_URL ?? null,
    zeroXApiKey: parsed.data.ZEROX_API_KEY ?? "",
    zeroXApiVersion: parsed.data.ZEROX_API_VERSION,
    alertWebhookUrl: parsed.data.ALERT_WEBHOOK_URL ?? null,
    alertWebhookToken: parsed.data.ALERT_WEBHOOK_TOKEN ?? null,
    metricsToken: parsed.data.METRICS_TOKEN ?? null,
    vaultProvider: parsed.data.VAULT_PROVIDER,
    externalSignerUrl: parsed.data.EXTERNAL_SIGNER_URL ?? null,
    externalSignerToken: parsed.data.EXTERNAL_SIGNER_TOKEN ?? null,
    externalSignerMtls: parsed.data.EXTERNAL_SIGNER_MTLS,
    externalSignerClientCert: parsed.data.EXTERNAL_SIGNER_CLIENT_CERT ?? null,
    externalSignerClientKey: parsed.data.EXTERNAL_SIGNER_CLIENT_KEY ?? null,
    externalSignerHealthUrl: parsed.data.EXTERNAL_SIGNER_HEALTH_URL ?? null,
    externalSignerSignTimeoutMs: parsed.data.EXTERNAL_SIGNER_SIGN_TIMEOUT_MS,
    externalSignerNonceStrategy: parsed.data.EXTERNAL_SIGNER_NONCE_STRATEGY,
  };
};

export type RuntimeConfig = ReturnType<typeof parseRuntimeEnv>;
